<?php

namespace Database\Seeders;

use App\Statuses\ProductStatus;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'brand_id' => 1,
                'model_id' => 1,
                'store_id' => 1,
                'name' => 'Civic',
                'main_photo' => 'bmw.jpg',
                'price' => 24000,
                'mileage' => 30,
                'year_of_construction' => 2020,
                'number_of_seats' => 5,
                'drive_type' => ProductStatus::DRIVE_FRONT,
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 4,
                'cylinder_capacity' => 2.0,
                'gears' => 'manual',
                'type' => 'used',
                'seat_type' => 'cloth',
                'sunroof' => false,
                'color' => 'red',
                'lights' => 'LED',
            ],
            [
                'brand_id' => 1,
                'model_id' => 2,
                'store_id' => 1,
                'name' => 'Accord',
                'main_photo' => 'bmw.jpg',
                'price' => 26500,
                'mileage' => 29,
                'year_of_construction' => 2021,
                'number_of_seats' => 5,
                'drive_type' => 'front',
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 4,
                'cylinder_capacity' => 1.5,
                'gears' => 'automatic',
                'type' => 'new',
                'seat_type' => 'leather',
                'sunroof' => true,
                'color' => 'blue',
                'lights' => 'Halogen',
            ],
            [
                'brand_id' => 2,
                'model_id' => 3,
                'store_id' => 1,
                'name' => 'Model 3',
                'main_photo' => 'bmw.jpg',
                'price' => 39990,
                'mileage' => 130,
                'year_of_construction' => 2021,
                'number_of_seats' => 5,
                'drive_type' => 'rear',
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 2,
                'cylinder_capacity' => 2,
                'gears' => 'automatic',
                'type' => 'new',
                'seat_type' => 'leather',
                'sunroof' => true,
                'color' => 'white',
                'lights' => 'LED',
            ],
            [
                'brand_id' => 3,
                'model_id' => 4,
                'store_id' => 1,
                'name' => 'Camry',
                'main_photo' => 'bmw.jpg',
                'price' => 30000,
                'mileage' => 28,
                'year_of_construction' => 2022,
                'number_of_seats' => 5,
                'drive_type' => 'front',
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 4,
                'cylinder_capacity' => 2.5,
                'gears' => 'automatic',
                'type' => 'new',
                'seat_type' => 'leather',
                'sunroof' => true,
                'color' => 'black',
                'lights' => 'Halogen',
            ],
            [
                'brand_id' => 4,
                'model_id' => 5,
                'store_id' => 1,
                'name' => 'Altima',
                'main_photo' => 'bmw.jpg',
                'price' => 28000,
                'mileage' => 27,
                'year_of_construction' => 2021,
                'number_of_seats' => 5,
                'drive_type' => 'front',
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 4,
                'cylinder_capacity' => 2.5,
                'gears' => 'automatic',
                'type' => 'new',
                'seat_type' => 'cloth',
                'sunroof' => false,
                'color' => 'silver',
                'lights' => 'LED',
            ],
            [
                'brand_id' => 5,
                'model_id' => 6,
                'store_id' => 1,
                'name' => 'Mustang',
                'main_photo' => 'bmw.jpg',
                'price' => 43000,
                'mileage' => 20,
                'year_of_construction' => 2022,
                'number_of_seats' => 4,
                'drive_type' => 'rear',
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 8,
                'cylinder_capacity' => 5.0,
                'gears' => 'manual',
                'type' => 'new',
                'seat_type' => 'leather',
                'sunroof' => false,
                'color' => 'yellow',
                'lights' => 'LED',
            ],
            [
                'brand_id' => 6,
                'model_id' => 7,
                'store_id' => 1,
                'name' => 'Wrangler',
                'main_photo' => 'bmw.jpg',
                'price' => 48000,
                'mileage' => 22,
                'year_of_construction' => 2022,
                'number_of_seats' => 5,
                'drive_type' => ProductStatus::DRIVE_REAR,
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 6,
                'cylinder_capacity' => 3.6,
                'gears' => 'manual',
                'type' => 'new',
                'seat_type' => 'cloth',
                'sunroof' => true,
                'color' => 'green',
                'lights' => 'Halogen',
            ],
            [
                'brand_id' => 7,
                'model_id' => 8,
                'store_id' => 1,
                'name' => 'Malibu',
                'main_photo' => 'bmw.jpg',
                'price' => 24500,
                'mileage' => 29,
                'year_of_construction' => 2021,
                'number_of_seats' => 5,
                'drive_type' => 'front',
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 4,
                'cylinder_capacity' => 1.5,
                'gears' => 'automatic',
                'type' => 'new',
                'seat_type' => 'cloth',
                'sunroof' => false,
                'color' => 'gray',
                'lights' => 'LED',
            ]]);
    }
}
