<?php

namespace Database\Seeders;

use App\Statuses\ProductStatus;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'brand_id' => 1,
                'model_id' => 1,
                'store_id' => 1,
                'structure_id' => 1,
                'main_photo' => 'bmw.jpg',
                'price' => 24000.00,
                'mileage' => 30,
                'year_of_construction' => 2020,
                'register_year' => 2020,
                'number_of_seats' => 5,
                'drive_type' => ProductStatus::DRIVE_FRONT,
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 4,
                'cylinder_capacity' => 2.0,
                'additional_features' => 'Air Conditioning, Bluetooth, Navigation',
                'gears' => 6, // Assuming manual = 6 gears
                'type' => ProductStatus::TYPE_USED,
                'seat_type' => ProductStatus::SEAT_CLOTH,
                'sunroof' => ProductStatus::SUNROOF_NO,
                'color' => 'red',
                'lights' => 'LED',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand_id' => 1,
                'model_id' => 2,
                'store_id' => 1,
                'structure_id' => 2,
                'main_photo' => 'bmw.jpg',
                'price' => 26500.00,
                'mileage' => 29,
                'year_of_construction' => 2021,
                'register_year' => 2021,
                'number_of_seats' => 5,
                'drive_type' => ProductStatus::DRIVE_FRONT,
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 4,
                'cylinder_capacity' => 1.5,
                'additional_features' => 'Leather Seats, Sunroof, Premium Audio',
                'gears' => 8, // Assuming automatic = 8 gears
                'type' => ProductStatus::TYPE_NEW,
                'seat_type' => ProductStatus::SEAT_LEATHER,
                'sunroof' => ProductStatus::SUNROOF_YES,
                'color' => 'blue',
                'lights' => 'Halogen',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand_id' => 2,
                'model_id' => 3,
                'store_id' => 1,
                'structure_id' => 3,
                'main_photo' => 'bmw.jpg',
                'price' => 39990.00,
                'mileage' => 130,
                'year_of_construction' => 2021,
                'register_year' => 2021,
                'number_of_seats' => 5,
                'drive_type' => ProductStatus::DRIVE_REAR,
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 2,
                'cylinder_capacity' => 2.0,
                'additional_features' => 'Autopilot, Glass Roof, Premium Interior',
                'gears' => 1, // Electric vehicles often have single gear
                'type' => ProductStatus::TYPE_NEW,
                'seat_type' => ProductStatus::SEAT_LEATHER,
                'sunroof' => ProductStatus::SUNROOF_YES,
                'color' => 'white',
                'lights' => 'LED',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand_id' => 3,
                'model_id' => 4,
                'store_id' => 1,
                'structure_id' => 4,
                'main_photo' => 'bmw.jpg',
                'price' => 30000.00,
                'mileage' => 28,
                'year_of_construction' => 2022,
                'register_year' => 2022,
                'number_of_seats' => 5,
                'drive_type' => ProductStatus::DRIVE_FRONT,
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 4,
                'cylinder_capacity' => 2.5,
                'additional_features' => 'JBL Audio, Dual Zone Climate Control',
                'gears' => 8,
                'type' => ProductStatus::TYPE_NEW,
                'seat_type' => ProductStatus::SEAT_LEATHER,
                'sunroof' => ProductStatus::SUNROOF_YES,
                'color' => 'black',
                'lights' => 'Halogen',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand_id' => 4,
                'model_id' => 5,
                'store_id' => 1,
                'structure_id' => 5,
                'main_photo' => 'bmw.jpg',
                'price' => 28000.00,
                'mileage' => 27,
                'year_of_construction' => 2021,
                'register_year' => 2021,
                'number_of_seats' => 5,
                'drive_type' => ProductStatus::DRIVE_FRONT,
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 4,
                'cylinder_capacity' => 2.5,
                'additional_features' => 'Keyless Entry, Rear View Camera',
                'gears' => 8,
                'type' => ProductStatus::TYPE_NEW,
                'seat_type' => ProductStatus::SEAT_CLOTH,
                'sunroof' => ProductStatus::SUNROOF_NO,
                'color' => 'silver',
                'lights' => 'LED',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand_id' => 5,
                'model_id' => 6,
                'store_id' => 1,
                'structure_id' => 6,
                'main_photo' => 'bmw.jpg',
                'price' => 43000.00,
                'mileage' => 20,
                'year_of_construction' => 2022,
                'register_year' => 2022,
                'number_of_seats' => 4,
                'drive_type' => ProductStatus::DRIVE_REAR,
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 8,
                'cylinder_capacity' => 5.0,
                'additional_features' => 'Performance Package, Sport Exhaust',
                'gears' => 6,
                'type' => ProductStatus::TYPE_NEW,
                'seat_type' => ProductStatus::SEAT_LEATHER,
                'sunroof' => ProductStatus::SUNROOF_NO,
                'color' => 'yellow',
                'lights' => 'LED',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand_id' => 6,
                'model_id' => 7,
                'store_id' => 1,
                'structure_id' => 7,
                'main_photo' => 'bmw.jpg',
                'price' => 48000.00,
                'mileage' => 22,
                'year_of_construction' => 2022,
                'register_year' => 2022,
                'number_of_seats' => 5,
                'drive_type' => ProductStatus::DRIVE_REAR,
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 6,
                'cylinder_capacity' => 3.6,
                'additional_features' => 'Off-road Package, Tow Package',
                'gears' => 6,
                'type' => ProductStatus::TYPE_NEW,
                'seat_type' => ProductStatus::SEAT_CLOTH,
                'sunroof' => ProductStatus::SUNROOF_YES,
                'color' => 'green',
                'lights' => 'Halogen',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand_id' => 7,
                'model_id' => 8,
                'store_id' => 1,
                'structure_id' => 8,
                'main_photo' => 'bmw.jpg',
                'price' => 24500.00,
                'mileage' => 29,
                'year_of_construction' => 2021,
                'register_year' => 2021,
                'number_of_seats' => 5,
                'drive_type' => ProductStatus::DRIVE_FRONT,
                'fuel_type' => ProductStatus::FUEL_PETROL,
                'cylinders' => 4,
                'cylinder_capacity' => 1.5,
                'additional_features' => 'Apple CarPlay, Android Auto',
                'gears' => 8,
                'type' => ProductStatus::TYPE_NEW,
                'seat_type' => ProductStatus::SEAT_CLOTH,
                'sunroof' => ProductStatus::SUNROOF_NO,
                'color' => 'gray',
                'lights' => 'LED',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
